// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MyBorderBox: typeof import('./src/components/component/MyBorderBox/index.vue')['default']
    MyCart: typeof import('./src/components/component/MyCart/index.vue')['default']
    MyFireworks: typeof import('./src/components/component/MyFireworks/index.vue')['default']
    MyHeader: typeof import('./src/components/MyHeader/index.vue')['default']
    MyMeteor: typeof import('./src/components/component/MyMeteor/index.vue')['default']
    MyRain: typeof import('./src/components/component/MyRain/index.vue')['default']
    MyStar: typeof import('./src/components/component/MyStar/index.vue')['default']
    MyToggle: typeof import('./src/components/component/MyToggle/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
